### ISSUE TITLE
Error with `Test Plot` algorithm

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-wps-web-client-module#26]
# Procedure
- Execute `Test Plot` algorithm.
- In console you get :
```
dataviz.js:306 Uncaught TypeError: Cannot read properties of null (reading 'locale')
    at buildPlot (dataviz.js:306:40)
    at Object.buildPlot (dataviz.js:533:18)
    at Object.success (getfile?targetmodule=wps&file=wps.js:743:39)
    at c (jquery-3.5.1.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2:29039)
    at l (jquery-3.5.1.min.js:2:79800)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2:82254)
```

**Comment by rldhont** [comment]
Issue in lizmap-web-client.

the lizmap buildPlot method can only be used if the project has dataviz configured. The way to fixed this issue is to fixed the way `datavizLayers` is provided in config.
