### ISSUE TITLE
WPS exit with code 139 randomly

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-wps-web-client-module#7]
Randomly when executing `make run` in tests directory i have those logs above.
Then in LWC I don't have algorithms displayed.

```
wps_1     | /usr/lib/python3/dist-packages/pyparsing.py:943: DeprecationWarning:
wps_1     | 
wps_1     | Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
wps_1     | 
wps_1     | /usr/lib/python3/dist-packages/pyparsing.py:3245: DeprecationWarning:
wps_1     | 
wps_1     | Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
wps_1     | 
wps_1     | /usr/share/qgis/python/plugins/processing/gui/wrappers.py:1757: DeprecationWarning:
wps_1     | 
wps_1     | invalid escape sequence \A
wps_1     | 
wps_1     | /usr/share/qgis/python/plugins/processing/gui/wrappers.py:1772: DeprecationWarning:
wps_1     | 
wps_1     | invalid escape sequence \A
wps_1     | 
wps_1     | 2020-06-03 07:53:47,147	[1]	ERROR	[qgis:1] Processing: Problem with SAGA installation: SAGA was not found or is not correctly installed
wps_1     | /usr/lib/python3/dist-packages/pyparsing.py:943: DeprecationWarning:
wps_1     | 
wps_1     | Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
wps_1     | 
wps_1     | /usr/lib/python3/dist-packages/pyparsing.py:3245: DeprecationWarning:
wps_1     | 
wps_1     | Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
wps_1     | 
wps_1     | /usr/share/qgis/python/plugins/processing/gui/wrappers.py:1757: DeprecationWarning:
wps_1     | 
wps_1     | invalid escape sequence \A
wps_1     | 
wps_1     | /usr/share/qgis/python/plugins/processing/gui/wrappers.py:1772: DeprecationWarning:
wps_1     | 
wps_1     | invalid escape sequence \A
wps_1     | 
wps_1     | 2020-06-03 07:53:47,147	[67]	ERROR	[qgis:67] Processing: Problem with SAGA installation: SAGA was not found or is not correctly installed
wps_1     | Traceback (most recent call last):
wps_1     |   File "/usr/share/qgis/python/plugins/processing/script/ScriptAlgorithmProvider.py", line 66, in load
wps_1     |     ScriptUtils.defaultScriptsFolder(),
wps_1     |   File "/usr/share/qgis/python/plugins/processing/script/ScriptUtils.py", line 51, in defaultScriptsFolder
wps_1     |     mkdir(folder)
wps_1     |   File "/usr/share/qgis/python/plugins/processing/tools/system.py", line 109, in mkdir
wps_1     |     os.mkdir(newdir)
wps_1     | FileExistsError: [Errno 17] File exists: '/home/qgis/.local/share/QGIS/QGIS3/profiles/default/processing/scripts'
wps_1     | 2020-06-03 07:53:47,177	[67]	INFO	[qgis:67] QGis processing initialized
wps_1     | 2020-06-03 07:53:47,178	[67]	DEBUG	= Registering provider 'script'
wps_1     | 2020-06-03 07:53:47,179	[67]	DEBUG	= Registering provider 'model'
wps_1     | 2020-06-03 07:53:47,185	[67]	INFO	Loaded plugin 'algorithms'
wps_1     | 2020-06-03 07:53:47,189	[67]	DEBUG	Starting ZMQ worker loop
tests_wps_1 exited with code 139

```

**Comment by dmarteau** [comment]
This appends sometime and seems to be related to some random uncatched python exception in qgis processing python code. I have no fix for this. 

And this error:
```
FileExistsError: [Errno 17] File exists: '/home/qgis/.local/share/QGIS/QGIS3/profiles/default/processing/scripts'
```
is getting on my  nerves from some time now....

**Comment by dmarteau** [comment]
@nboisteault:  do remember to update your docker images frequently !

**Comment by dmarteau** [comment]
AFAIK: python code is cleaner in Qgis 3.10.

**Comment by dmarteau** [comment]
@nboisteault this is an issue for [py-qgis-wps](https://github.com/3liz/py-qgis-wps) please open an issue for that project.

**Comment by nboisteault** [comment]
Done : https://github.com/3liz/py-qgis-wps/issues/5
